config/routes.rb
Rails.application.routes.draw do
  resources :dishes
  resources :comments
  
  root 'dishes#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :dish
end

app/models/dish.rb
class Dish < ActiveRecord::Base
	validates :image, presence: true
	validates :name, presence: true
	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "640x" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_dish

	def create  
		@comment = @dish.comments.build(comment_params)

		if @comment.save
			flash[:success] = "You commented the hell out of that post!"
			redirect_to :back
		else
			flash[:alert] = "Check the comment form, something went horribly wrong."
			render root_path
		end
	end

	def destroy  
  		@comment = @dish.comments.find(params[:id])

  		@comment.destroy
  		flash[:success] = "Comment deleted :("
  		redirect_to root_path
	end  

	private

	def comment_params  
		params.require(:comment).permit(:content, :username)
	end

	def set_dish 
		@dish = Dish.find(params[:comment][:id])
	end  
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :description, :image, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<%= form_for @dish, html: { multipart: true } do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="menuItem">
    <%= f.label :menuItem %><br>
    <%= f.text_field :menuItem %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dishes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.name %></td>
        <td><%= dish.description %></td>
        <td><%= image_tag dish.image.url(:med) %></td>
        <td><%= dish.rating %></td>
        <td><%= link_to 'Show', dish %></td>
        <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
        <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dish.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @dish.image.url(:med) %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @dish.rating %>
</p>



<div class="posts-wrapper row">
	<% if @dish.comments %>
		<% @dish.comments.each do |comment| %>
		<div class="comment">
			<div class="username">
				<%= comment.username %>
			</div>
			<div class="comment-content">
				<%= comment.content %>
			</div>
		</div>
		<% end %>
	<% end %>
</div>

	<div class="comment-form">
		<%= form_for [@dish.comments.new] do |f| %>
			<%= f.hidden_field :id, :value => @dish.id%>
			<%= f.text_field :username, placeholder: 'Your Name' %>
			<%= f.text_field :content, placeholder: 'Add a comment...' %>
			<%= submit_tag("Comment") %>
		<% end %>
	</div>




<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ABiteOfUST</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "ABiteOfUST", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "New Dish", new_dish_path %>
        </li>
        <li>
          <%= link_to "About", '#' %>
        </li>
      </ul>
    </div>
  </div>
</nav>


<%= yield %>

</body>
</html>